# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   creationTimestamp: null
#   labels:
#     app: demo
#   name: demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: demo
#   strategy: {}
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: demo
#     spec:
#       containers:
#       - image: nginx
#         name: nginx
#         resources: {}
# status: {}


# ---

# apiVersion: s3.aws.m.upbound.io/v1beta1
# kind: Bucket
# metadata:
#   labels:
#     testing.upbound.io/example-name: crossplane-bucket
#   name: demo-crossplane-bucket
#   namespace: default
# spec:
#   forProvider:
#     region: eu-central-1
