argocd-apps:
  applications:
# Argo can manage argo itself, thanks to its stateless nature we always have backwards compatability with helm disaster recovery is to fix and run helm upgrade --install argo helm/argo -n argo
  - name: argo
    namespace: argo
    project: infra
    sources:
     - repoURL: https://github.com/koorikla/argo-stack
       path: helm/argo
       targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: argo
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

# Chart to manage Argo Internals - applications, appsets, projects etc (this chart)
  - name: app-of-apps
    namespace: argo
    project: infra
    sources:
     - repoURL: https://github.com/koorikla/argo-stack
       path: helm/app-of-apps
       targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: argo



  - name: workflow-components
    namespace: argo
    project: infra
    sources:
     - repoURL: https://github.com/koorikla/argo-stack
       path: workflow-components
       targetRevision: main
       directory:
        recurse: true    
    destination:
      server: https://kubernetes.default.svc
      namespace: argo


  projects:
  - name: infra
    namespace: argo
    finalizers:
    description: Infra Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
