argocd-apps:
  applications:
# Argo can manage argo itself, disaster recovery is to revert and run helm update --install again
  - name: argo
    namespace: argo
    project: infra
    sources:
     - repoURL: https://github.com/koorikla/argo-stack
       path: helm/argo
       targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: argo
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
      syncOptions:
      - CreateNamespace=true
# Chart to manage Argo Internals - applications, appsets, projects etc (this chart)
  - name: app-of-apps
    namespace: argo
    project: infra
    sources:
     - repoURL: https://github.com/koorikla/argo-stack
       path: helm/app-of-apps
       targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: argo


  projects:
  - name: infra
    namespace: argo
    finalizers:
    description: Infra Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
